baseURL = "https://www.amusement-creators.info/"
languageCode = "ja-jp"
title = "Amusement Creators"
theme = "ananke"
background_color_class = "bg-white"

# デフォルトのヒーローヘッダーを設定
featured_image = "/images/hero.png"

# 日本語を使った記事でサマリの文字数がおかしくなるのを防ぐ
hasCJKLanguage = true

# 記事の本文で絵文字(ex. `:+1:, :muscle:`)を有効化
enableEmoji = true

# コードにハイライトを適用
pygmentsCodeFences = true

[taxonomies]
  author = "authors"
  tag = "tags"
  category = "categories"

# hugoで使用されているmarkdownパーサーの設定
[blackfriday]
# 記事の文中のリンクはすべて別タブで開く
hrefTargetBlank = true

[params]
  description = "筑波大学 Amusement Creators"
  images = ["/images/hero.png"]
  twitter = "https://twitter.com/ac_is_not_am"


[menu]
  [[menu.main]]
    name = "About"
    identifier = "about"
    url = "/about/"

  [[menu.main]]
    name = "Members"
    identifier = "members"
    url = "/members/"

  [[menu.main]]
    name = "News"
    identifier = "news"
    url = "/post/news"

  [[menu.main]]
    name = "Works"
    identifier = "works"
    url = "/post/works"

  [[menu.main]]
    name = "Articles"
    identifier = "articles"
    url = "/post/articles"
